name: Publish

on:
  push:
    branches:
      - main
      - gh-pages
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        ref: gh-pages

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily update
      run: |
        python best-invidious-server.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        branch: gh-pages
